enableScripts: false
enableTelemetry: false
npmMinimalAgeGate: 3d
npmPreapprovedPackages:
  # The intention is to publish the translations as soon as possible,
  # so there is no point in waiting several days for this.
  # This can also be considered a fairly trustworthy package.
  - ra-core

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.15.0.cjs
