name: Run checks

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-types:
    runs-on: ubuntu-latest

    concurrency:
      group: check-types
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Run ts:check
        run: yarn ts:check
