name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn npm publish --provenance
